### ISSUE TITLE
Need to be able hide author page

### ISSUE THREAD

**Issue by jeremyBass** [washingtonstateuniversity/WSUWP-Platform#226]
I was doing some tests on search.wsu.edu and noticed, that when I did a quick test search on `jeremy` I get some results from Google that are bad SEO for us.  tons of links like

* hub.wsu.edu/everett-engineering-club/author/jeremy-felt/
* ga-15.web.wsu.edu/author/jeremy-bass/
* web.wsu.edu/openlab/author/jeremy-felt/
*  ...

and tons more, but they are blanks, and not really pages I think we would be wanting out there.  Google searched them, weighed them, and I'm sure our overall score was lowered based on all the *insert animal name* engine rules.  Maybe it's of no concern but I would bet that it is of some and we should pick off this detail sooner then later for the good of the overall WSU SEO.

**Comment by jeremyfelt** [comment]
This was added to the Spine Parent Theme in https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme/pull/265
