### ISSUE TITLE
Use NID to View Password-Protected Pages

### ISSUE THREAD

**Issue by jbickelhaupt** [washingtonstateuniversity/WSUWP-Platform#282]
We can currently set a specific password to share for a select group of visitors to enter and view password-protected pages. These are visitors that are trying to view public pages on the site that have password protection enabled. Would like the ability to give visitors (students/fac/staff) access to those pages by entering their NID instead of a shared password. Site admins could then establish an approved list of NIDs that are granted access to the page.

**Comment by jeremyfelt** [comment]
Tracking that here: https://github.com/washingtonstateuniversity/WSUWP-Platform/issues/238
