### ISSUE TITLE
Draft preview for a site with subdirectory is busted.

### ISSUE THREAD

**Issue by clintyoung** [washingtonstateuniversity/WSUWP-Platform#355]
I don't know if this is just because the subdirectory site is using a different theme, but please see example of issue below.

Site: cvm.wsu.edu/rta
![image](https://cloud.githubusercontent.com/assets/5806094/17156904/08a9ccf0-5341-11e6-88fd-bf45b879d37d.png)

As long as the page is in draft state, this is what I get on the preview tab:
![image](https://cloud.githubusercontent.com/assets/5806094/17156930/31d82a22-5341-11e6-8efa-453464e01bd0.png)

**Comment by jeremyfelt** [comment]
Nice. I'm able to reproduce this locally when Edit Flow is enabled, so it must be doing something to the preview link. Digging further.

**Comment by jeremyfelt** [comment]
This was fixed in https://github.com/washingtonstateuniversity/WSUWP-Build-Plugins-Public/commit/4ccb8de19fa9496b24bacf6bfd2aee83ca792229 and a pull request has been submitted upstream to Edit Flow.
